import { parseExtensionActionsBlock, type ExtensionDeclarativeAction } from '@/services/lego_blocks/integrations/extensionActionBlock'

export interface ExtensionBuilderPromptSet {
  systemPrompt: string
  userPrompt: string
}

export interface ExtensionBuilderDraft {
  featureId: string
  name: string
  description: string
  permissions: string[]
  actions: ExtensionDeclarativeAction[]
  promptMarkdown: string
  uiSchema: Record<string, unknown>
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64)
}

function normalizeText(value: string): string {
  return value.replace(/\r\n/g, '\n').trim()
}

function extractJsonCandidate(value: string): string {
  const trimmed = value.trim()
  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)
  return fenced ? fenced[1] : trimmed
}

export function buildExtensionBuilderPromptBlock(intent: string): ExtensionBuilderPromptSet {
  const normalizedIntent = normalizeText(intent)
  return {
    systemPrompt: [
      'You generate safe declarative extension artifacts for a local-first app.',
      'Return strict JSON only (no markdown prose).',
      'Schema:',
      '{',
      '  "featureId": "kebab-case-id",',
      '  "name": "Display Name",',
      '  "description": "Short description",',
      '  "permissions": ["organizer:read" | "organizer:write" | "tools:pdf" | "tools:transcript" | "tools:excalidraw"],',
      '  "actions": [{',
      '    "id": "kebab-case",',
      '    "label": "Button label",',
      '    "target": "sidebar-bottom" | "thought-context-actions",',
      '    "capability": "capability name",',
      '    "input": { "any": "json with {{context.someKey}} placeholders" }',
      '  }],',
      '  "promptMarkdown": "markdown instructions for users",',
      '  "uiSchema": { "version": 1, "slots": [] }',
      '}',
      'Do not include dynamic code. Prefer declarative capability-backed actions.',
    ].join('\n'),
    userPrompt: [
      'Generate extension artifacts for this feature intent:',
      normalizedIntent,
    ].join('\n\n'),
  }
}

export function parseExtensionBuilderDraftFromAiBlock(responseText: string): ExtensionBuilderDraft | null {
  const candidate = extractJsonCandidate(responseText)
  let parsed: unknown
  try {
    parsed = JSON.parse(candidate)
  } catch {
    return null
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return null
  const record = parsed as Record<string, unknown>

  const featureIdRaw = typeof record.featureId === 'string' ? record.featureId.trim() : ''
  const nameRaw = typeof record.name === 'string' ? record.name.trim() : ''
  const descriptionRaw = typeof record.description === 'string' ? record.description.trim() : ''
  const promptRaw = typeof record.promptMarkdown === 'string' ? record.promptMarkdown : ''
  const permissionsRaw = Array.isArray(record.permissions) ? record.permissions : []
  const actionsParsed = parseExtensionActionsBlock(record.actions)
  if (!actionsParsed.ok) return null

  const featureId = slugify(featureIdRaw || nameRaw || 'generated-extension')
  if (!featureId) return null
  const name = nameRaw || 'Generated Extension'
  const description = descriptionRaw || 'Generated by AI feature builder.'
  const permissions = permissionsRaw
    .filter(value => typeof value === 'string')
    .map(value => value.trim())
    .filter(Boolean)
  const promptMarkdown = normalizeText(promptRaw) || buildFallbackPromptMarkdown(name, description)
  const uiSchema = (
    record.uiSchema && typeof record.uiSchema === 'object' && !Array.isArray(record.uiSchema)
      ? record.uiSchema as Record<string, unknown>
      : { version: 1, slots: [] }
  )

  return {
    featureId,
    name,
    description,
    permissions: dedupeStrings(permissions),
    actions: actionsParsed.actions,
    promptMarkdown,
    uiSchema,
  }
}

export function buildFallbackExtensionBuilderDraftBlock(intent: string): ExtensionBuilderDraft {
  const normalized = normalizeText(intent)
  const featureId = slugify(normalized.split('\n')[0] || 'generated-feature') || 'generated-feature'
  const name = normalized.split('\n')[0].slice(0, 64) || 'Generated Feature'
  const description = normalized || 'Generated by extension builder.'

  const actions: ExtensionDeclarativeAction[] = [
    {
      id: 'list-folders',
      label: 'List Folders',
      target: 'sidebar-bottom',
      capability: 'tools.folders.list',
      input: { limit: 12 },
      description: 'Quickly list top folders from the vault.',
    },
    {
      id: 'read-frontmatter',
      label: 'Read Frontmatter',
      target: 'thought-context-actions',
      capability: 'organizer.node.read_frontmatter',
      input: {
        filePath: '{{context.filePath}}',
      },
      description: 'Inspect selected thought metadata.',
    },
  ]

  return {
    featureId,
    name,
    description,
    permissions: ['organizer:read'],
    actions,
    promptMarkdown: buildFallbackPromptMarkdown(name, description),
    uiSchema: {
      version: 1,
      slots: [
        { id: 'sidebar-bottom', description: 'Global sidebar actions' },
        { id: 'thought-context-actions', description: 'Actions on selected thought context' },
      ],
    },
  }
}

function buildFallbackPromptMarkdown(name: string, description: string): string {
  return [
    `# ${name}`,
    '',
    description,
    '',
    '## Generated Guidance',
    '',
    '- Review extension permissions before activation.',
    '- Keep actions declarative and capability-scoped.',
    '- Use thought-context placeholders like `{{context.filePath}}` as needed.',
  ].join('\n')
}

function dedupeStrings(values: string[]): string[] {
  const next: string[] = []
  for (const value of values) {
    if (!next.includes(value)) next.push(value)
  }
  return next
}

